spring:
  profiles:
    active: http, gemini, console-runner

  ai:
    chat:
      client: 
        enabled: false

    ollama:
      base-url: ${OLLAMA_BASE_URL:http://localhost:11434}
      chat:
        options:
          model: ${OLLAMA_MODEL:qwen2.5:1.5b}
          temperature: 0.2

    google:
      genai:
        api-key: ${GEMINI_API_KEY:gemin_key}
        chat:
          options:
            model: ${GEMINI_MODEL:gemini-2.5-flash}
            temperature: 0.2 

    openai:
      api-key: ${HUGGING_FACE_API_KEY:hugging_face_api_key}
      base-url: ${HUGGING_FACE_BASE_URL:https://router.huggingface.co}
      chat:
        options:
          model: ${OPENAI_MODEL:openai/gpt-oss-120b:groq}
          temperature: 0.2 

logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, env

atracio:
  base-url: ${ATRACIO_BASE_URL:https://demo.prod.atracio.com}
  http:
    connect-timeout-ms: 100000
    read-timeout-ms: 100000