spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:mock}

management:
  endpoints:
    web:
      exposure:
        include: health, env

atracio:
  base-url: ${ATRACIO_BASE_URL:https://demo.prod.atracio.com}